workflows:
  build-expo-apk:
    name: Build Expo APK
    max_build_duration: 60

    environment:
      node: 18

    scripts:
      - name: Go to project root
        script: cd $CM_BUILD_DIR

      - name: Install Expo CLI
        script: npm install -g expo-cli

      - name: Install dependencies (ignore peer deps)
        script: npm install --legacy-peer-deps

      - name: Build APK
        script: npx expo build:android -t apk --no-wait

    artifacts:
      - '*.apk'
