workflows:
  build-expo-apk:
    name: Build Expo APK
    max_build_duration: 60

    environment:
      node: 18

    scripts:
      - name: Install Yarn
        script: npm install -g yarn

      - name: Install Expo CLI
        script: npm install -g expo-cli

      - name: Install dependencies
        script: yarn install

      - name: Build APK
        script: npx expo build:android -t apk --no-wait

    artifacts:
      - '*.apk'
