workflows:
  build-expo-apk:
    name: Build Expo APK via EAS
    max_build_duration: 60

    environment:
      node: 18

    scripts:
      - name: Go to project root
        script: cd $CM_BUILD_DIR

      - name: Install Expo CLI
        script: npm install -g expo-cli

      - name: Install EAS CLI
        script: npm install -g eas-cli

      - name: Install dependencies
        script: npm install --legacy-peer-deps

      - name: Login to Expo using token
        script: |
          export EXPO_TOKEN=OgxnL3tG5oewDeI2fUbMJAvY4o4L8aNmHDZOMU5-
          eas whoami

      - name: Build APK with EAS
        script: eas build -p android --non-interactive

    artifacts:
      - 'dist/**/*.apk'
