workflows:
  build-expo-apk:
    name: Build Expo APK
    max_build_duration: 60

    environment:
      node: 18

    scripts:
      # انتقل إلى مجلد المشروع الصحيح (Root)
      - name: Go to project root
        script: cd $CM_BUILD_DIR

      # تثبيت Expo CLI
      - name: Install Expo CLI
        script: npm install -g expo-cli

      # تثبيت dependencies
      - name: Install dependencies
        script: yarn install

      # بناء APK
      - name: Build APK
        script: npx expo build:android -t apk --no-wait

    artifacts:
      - '*.apk'
